### ISSUE TITLE
data: analytics, experimentation, user journeys

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape#97]
# Context

Related to https://github.com/tloncorp/landscape-apps/issues/2002

We are currently flying blind and have little insight into:

- how users are navigating and interacting with Landscape
- what features are critical and need attention vs what can be deprioritized

# Changes

- [ ] add opt-in toggle for telemetry
- [ ] add JS script to frontend
- [ ] POST events from backend agent to PostHog
- [ ] fire events at key stages of the user journey (e.g., user installed an app, user )
- [ ] build funnels based on aforementioned events in PostHog for analysis and future iteration
- [ ] use A/B testing to experiment with copy, designs, etc

# TODO

- [ ] which business questions are we trying to answer? which funnels do we care about? what are the key stages of those funnels?

**Comment by lukestiles** [comment]
This one is in the future and contingent on how we communicate around this. clear web is first. :)
